# Generated by Django 4.2.5 on 2023-09-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPietra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60)),
                ('hood', models.CharField(max_length=60)),
                ('num', models.IntegerField()),
                ('d_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
            ],
        ),
    ]
